# Input file for Retrainer

[teacher_model]
file_path = "example-methanol-model.bson"

[student_model]
file_name = "retrained-model.bson"
structure = [8, 10, 8, 1]
activations = ["identity", "relu", "identity"]
use_bias = true
precision = "f64"

[training]
epochs = 2000000
learning_rate = 0.001
input_scale_coef = 16

[testing]
samples_num = 10000
