# Input file for Retrainer

[teacher_model]
file_path = "model-iter-101.bson"

[student_model]
file_name = "output_model.bson"
structure = [8, 10, 8, 1]
activations = ["identity", "relu", "identity"]
use_bias = true
precision = "f64"

[training]
epochs = 20000
learning_rate = 0.0001
input_scale_coef = 16

[testing]
samples_num = 1000
